name: medical_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  device_preview: ^1.2.0
  lottie: ^3.3.1
  table_calendar: ^3.1.3
  dotted_border: ^2.1.0
  go_router: ^14.7.2
  flutter_launcher_icons: ^0.14.3
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  awesome_dialog: ^3.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lottie/
    - lib/core/views/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

